import "./global.css";
import Image from "next/image";
import localFont from "next/font/local";
/* FONTS */
// import { Noto_Sans_JP } from "next/font/google";
import { Figtree } from "next/font/google";
/* DIRECTUS */
import directus from "@/lib/directus";
import { notFound } from "next/navigation";
import { readItems } from "@directus/sdk";
/* COMPONENTS */
import Nav from "@/components/Nav";
import Logo from "@/components/Logo";
/* MUI */
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
/* SLICK CAROUSEL */
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

/* FONTS */
const metropolis = localFont({
  src: [
    {
      path: "./fonts/Metropolis-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Metropolis-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Metropolis-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Metropolis-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Metropolis-ExtraBold.otf",
      weight: "800",
      style: "normal",
    },
  ],
});

const noto_sans_jp = localFont({
  src: [
    {
      path: "./fonts/NotoSansJP-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/NotoSansJP-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/NotoSansJP-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/NotoSansJP-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/NotoSansJP-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
});
/* DIRECTUS */
async function getPages() {
  try {
    return await directus.request(
      readItems("pages", {
        sort: ["sort"],
        fields: ["*", "*.*", { file: ["*", "*.*"] }],
        filter: {
          _and: [
            // {
            //   status: {
            //     _eq: "published",
            //   },
            // },
            {
              sort: {
                _neq: 5, // Exclude the page with sort 5
              },
            },
          ],
        },
      })
    );
  } catch (error) {
    notFound();
  }
}

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }) {
  const pages = await getPages();
  return (
    <html
      lang="en"
      className={`${noto_sans_jp.className} ${metropolis.className}`}
    >
      <body>
        <AppRouterCacheProvider>
          {/* <Image
            priority
            src="/logo_hf.svg"
            alt="Hong Foundation Logo"
            width={120}
            height={210}
            style={{
              position: "absolute",
              top: 14,
              left: 0,
              zIndex: 999,
            }}
          /> */}
          <Logo />
          <div>
            <Nav pages={pages} />
          </div>
          <div>{children}</div>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
